input {
  tcp {
    port => 5000
    codec => json_lines
  }
}
filter {
  mutate {
    remove_field => ["password", "authorization", "cookie"]
  }
}
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "microservices-logs-%{+YYYY.MM.dd}"
  }
}
